new rebuild script to handle ffmpeg repo refreshing, patching, config…
SquirrelsLLC/ffmpeg-patches pull request #1
Opened 2019-06-04 20:49 UTC by PierceLBrooks

…uration, compilation, and installation

2019-06-04 21:20 UTC, stack requested changes
I think this looks good if you take out the unneeded calls to `sudo`.

2019-06-04 21:20 UTC, stack commented on rebuild.rb
> +  command = ["sudo", "./configure", "--enable-shared", "--disable-static", "--enable-openssl", "--prefix=/usr/local/"]
Only `make install` should be run with `sudo`.

2019-06-04 21:20 UTC, stack commented on rebuild.rb
> +  command = ["sudo", "make"]
Only `make install` should be run with `sudo`.

2019-06-04 23:08 UTC, PierceLBrooks commented
@stack:
[https://github.com/SquirrelsLLC/ffmpeg-patches/pull/1/commits/7f5683efffa0ea662dbec0bd96d5b50cb664ca5b](this commit) should resolve your request

2019-06-06 13:34 UTC, stack commented
Two thoughts on this:

1. Should we be doing the `sudo apt-get build-dep libavcodec ...` stuff in here?
2. Should the first `make` call have the `-j` option enabled, so that it does parallel builds?

2019-06-06 13:43 UTC, PierceLBrooks commented
I can add the `sudo apt-get build-dep` calls and build parallelization parameter to `make` now.

2019-06-06 16:52 UTC, stack commented
Looks good!

2019-06-06 16:52 UTC, merged